### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by ofir-dl** [YoungXIAO13/PoseContrast#1]
Hi,
Nice work :)
Could you please share a pretrained Pascal3D model?

Thanks!

**Comment by YoungXIAO13** [comment]
Hi @ofir-dl ,

Thanks for your interests! I have updated the README, you can now find the command to download the model trained on Pascal3D [here](https://github.com/YoungXIAO13/PoseContrast#3-download-pretrained-models)

**Comment by ofir-dl** [comment]
Thanks it's working :)

I would like to run inference on StanfordCars dataset for pose estimation.
Seems that your dataset already has bounding boxes corresponding to the objects within its images.

Does it mean I should first detect the cars and then use your model for the pose estimation?
Do you plan to add inference support to this repo?

Thank you so much!

**Comment by YoungXIAO13** [comment]
Yes, the input to viewpoint estimation network is cropped image, where the bounding boxes can be given by ground truth or detected by an object detection model.

For class-agnostic object detection, you can use the class-agnostic MaskRCNN trained on MS-COCO in this [repo](https://github.com/dulucas/ClassAgnostic_MaskRCNN) for detecting cars in StanfordCars images.
